### ISSUE TITLE
Rule Idea: `selector-pseudo-element-no-content-in-before-and-after`

### ISSUE THREAD

**Issue by evilebottnawi** [itgalaxy/stylelint-config-itgalaxy#3]
Invalid:

``` css
a::before {
  color: red;
}
```
